services:
  admin-api:
    container_name: 'admin-api'
    image: "protofy/workspace"
    entrypoint: "yarn admin-api-prod"
    environment:
      - MQTT_URL=mqtt://localhost:8883
      - API_URL=http://proxy:8000
      - NODE_ENV=production
    volumes:
      - ../../:/workspace
      - protofy_modules:/workspace/node_modules
volumes:
  protofy_modules:
    external: true